### ISSUE TITLE
Won't run: Form item missing type (file)

### ISSUE THREAD

**Issue by hopeseekr** [apideck-libraries/postman-to-k6#93] opened 2022-12-15 21:20 UTC
I get this when I run it:

```
$ postman-to-k6 api.postman.json
Form item missing type (file)
```
NodeJS v16.18.1
Ubuntu 20.04.4 LTS

**Comment by thim81** [comment] 2022-12-22 08:00
Hi @hopeseekr ,

The postman-to-k6 converter does not properly support file uploads.
We had started with adding the capability, but due to some limited available time not made enough progress to release the feature.

It is still on the feature list and it will come, don't know when at this time.

**Comment by thim81** [comment] 2023-01-14 15:48
hi @hopeseekr 

We just released v[.18.7 of postman-to-k6](https://github.com/apideck-libraries/postman-to-k6/releases/tag/v1.8.7), which introduces the support for file uploads.
The conversion from Postman uploads can take various shapes, so I tried to bring support for the binary upload.
Let me know if you have other use cases or run into other issues.

**Comment by thim81** [comment] 2023-01-16 08:18
@hopeseekr If the issue is resolved, feel free to close this item.

**Closed** 2024-07-20 18:02 UTC
