### ISSUE TITLE
Post request incorrectly exported from Postman to k6

### ISSUE THREAD

**Issue by jekakos** [apideck-libraries/postman-to-k6#80] opened 2022-08-31 12:38 UTC
Hi! 
I faced the following problem:
In Postman (Version 9.28.1) I have POST request with Content-Type="application/x-www-form-urlencoded"

<img width="894" alt="image" src="https://user-images.githubusercontent.com/80619441/187679685-eab9420a-e5aa-4b50-ad19-289dae3c5823.png">

After export collection I have

```
"request": {
"method": "POST",
"header": [
	{
		"key": "Content-Type",
		"value": "application/json",
		"type": "text"
	}
],
```

Because of this, the k6 request returned a 400 error and I could not understand what was wrong for a long time.

**Comment by jekakos** [comment] 2022-08-31 12:47
Sorry, I realized it's a postman problem 🙃
If you work closely, please let them know.

**Comment by thim81** [comment] 2022-09-01 12:39
Hi @jekakos 

Postman excludes "default" headers from the export, which results in missing headers when making the requests.
Have a look at: https://github.com/apideck-libraries/postman-to-k6/discussions/42#discussioncomment-2271512 >> Missing headers.

The item also mentions some work-a-rounds to overcome the situation.

**Comment by thim81** [comment] 2022-09-01 12:39
If the work-a-round helped, feel free to close the issue.

**Comment by thim81** [comment] 2022-11-12 18:49
Closing the issue, because of inactivity. Feel free to reopen if the issue is still occurring and the work-a-round did not solved your issue.

**Closed by thim81** 2022-11-12 18:49 UTC
