### ISSUE TITLE
Requests wrongly reusing headers from previous requests?

### ISSUE THREAD

**Issue by kuikiker** [apideck-libraries/postman-to-k6#98] opened 2023-02-06 22:17 UTC
I converted a postman collection to K6 but I cannot properly run it. After analysing the HTTP requests with Fiddler I noticed that some requests are wrongly reusing headers from previous requests.
For instance:
1. Request to **/login** (user/pass)-> **OK** (no Content-Type is specified so the default and correct application/x-www-form-urlencoded value is sent).
2. Request to **/endpoint1** using an Authorization bearer header obtained from the previous request. -> **OK**
3. Another request to **/login** (which is a verbatim copy of the first request) -> **FAIL**, due to wrong headers (**Content-Type: application/json** & **Authorization: Bearer xxxxxxxx**) that seems to be coming from the previous request to /endpoint1

Is there something I can do to avoid this behaviour? 
I have tried to manually add the **Content-Type: application/x-www-form-urlencoded** header to the /login requests but the second request to the /login still fails due to the incorrect **Authorization: bearer xxxxxxxx** header, even though a 'basic' auth is defined for these requests.

Thanks

**Comment by thim81** [comment] 2023-02-07 08:22
hi @kuikiker 

A lot of these things you mentioned often are linked to the Postman collection.
Would it be possible to share the Postman collection (with fake credentials), so we can see what happens in the Postman collection and what K6 scripts are generated.

**Comment by kuikiker** [comment] 2023-02-07 14:00
Hi @thim81 ,
I have left the bare minimum of my Postman collection; using fake credentials and only leaving the requests until the one to /login that fails (wrong **Content-Type** & **Authorization** headers)

Find attached the Postman collection and the generated K6 script (where I only commented the setTimeout function which is not recognized).

[postmanToK6.zip](https://github.com/apideck-libraries/postman-to-k6/files/10675719/postmanToK6.zip)

**Comment by thim81** [comment] 2023-03-21 07:58
hi @kuikiker 
I havent gotten around to look into this, apologies. I hope to find some time in the coming weeks.

**Comment by furiousdog** [comment] 2023-06-02 08:21
I have the same problem with `X-Client-Id` header in my scenario. It might only be fixed if I set the value to `null`.

**Comment by thim81** [comment] 2024-07-11 11:19
hi @kuikiker @furiousdog 

Is this still happening?

**Comment by titanzx** [comment] 2024-07-30 10:40
> hi @kuikiker @furiousdog
> 
> Is this still happening?

Yes it is

**Comment by thim81** [comment] 2024-07-30 10:42
hi @titanzx 

We tried to reproduce it with the sample provided but it looked OK.

Do you have a simple example that you can share, that we can use for reproducing it?
It would be helpful to have a simple Postman collection, the postman-to-k6 settings and the expected, correct output.

**Comment by titanzx** [comment] 2024-07-30 10:54
> hi @titanzx
> 
> We tried to reproduce it with the sample provided but it looked OK.
> 
> Do you have a simple example that you can share, that we can use for reproducing it? It would be helpful to have a simple Postman collection, the postman-to-k6 settings and the expected, correct output.

`  group("Block3", function() {
    group("KYC_PDPA", function() {
      postman[Request]({
        name: "KYC",
        id: "b7bbf1c8-650a-42e3-a400-01a50c8a7fc7",
        method: "GET",
        address: "{{https}}{{host}}{{url_kyc}}",
        headers: {
          "X-Correlation-Id": "{{$randomUUID}}",
          TimeStamp: "{{timestamp}}",
          "Content-Signature": "{{signature_key}}"
        },
        pre() {
        },
        post(response) {
          var json = pm.response.json();

          pm.test("Message should be success", function() {
            pm.expect(json.status.message).to.eql("success");
          });

          pm.test("Status code is 200", function() {
            pm.expect(pm.response.code).to.eql(200);
          });
        },
        auth(config, Var) {
          config.headers.Authorization = `Bearer ${pm[Var]("access_token")}`;
        }
      });

      postman[Request]({
        name: "PDPA",
        id: "6b1a5943-3e7a-4b28-9296-438f62f2e9ec",
        method: "GET",
        address: "{{https}}{{host}}{{url_pdpa}}",
        headers: {
          "X-Correlation-Id": "{{$randomUUID}}",
          TimeStamp: "{{timestamp}}",
          "Content-Signature": "{{signature_key}}"
        },
        pre() {
        },
        post(response) {
          var json = pm.response.json();

          pm.test("Message should be success", function() {
            pm.expect(json.status.message).to.eql("success");
          });

          pm.test("Status code is 200", function() {
            pm.expect(pm.response.code).to.eql(200);
          });
        },
        auth(config, Var) {
          config.headers.Authorization = `Bearer ${pm[Var]("access_token")}`;
        }
      });
    });
  });

  group("Block3.5", function() {
    group("My_Widget", function() {
      postman[Request]({
        name: "My_Tax",
        id: "071d6899-2800-4ee7-b56b-97379a035eb6",
        method: "POST",
        address: "{{https}}{{host}}{{url_my_widget}}",
        data:
          '{\n    "isLogin": true,\n    "widget_id": "0",\n    "callFrom": "my-tax"\n}',
        headers: {
          "X-Correlation-Id": "{{$randomUUID}}",
          deviceId: "{{deviceIdEncrypt}}",
          Timestamp: "{{timestamp}}"
        },
        pre() {
        },
        post(response) {
          var json = pm.response.json();

          pm.test("Message should be success", function() {
            pm.expect(json.status.message).to.eql("success");
          });

          pm.test("Status code is 200", function() {
            pm.expect(pm.response.code).to.eql(200);
          });
        }
      });
    })
  })`

**Comment by titanzx** [comment] 2024-07-30 11:03
> hi @titanzx
> 
> We tried to reproduce it with the sample provided but it looked OK.
> 
> Do you have a simple example that you can share, that we can use for reproducing it? It would be helpful to have a simple Postman collection, the postman-to-k6 settings and the expected, correct output.

**Postman Collection**
<img width="483" alt="image" src="https://github.com/user-attachments/assets/e737a5e1-6049-4d6a-88db-b4b6faa75b13">

**K6 Script**
```
  group("Block3", function() {
    group("KYC_PDPA", function() {
      postman[Request]({
        name: "KYC",
        id: "b7bbf1c8-650a-42e3-a400-01a50c8a7fc7",
        method: "GET",
        address: "{{https}}{{host}}{{url_kyc}}",
        headers: {
          "X-Correlation-Id": "{{$randomUUID}}",
          TimeStamp: "{{timestamp}}",
          "Content-Signature": "{{signature_key}}"
        },
        pre() {
        },
        post(response) {
          var json = pm.response.json();

          pm.test("Message should be success", function() {
            pm.expect(json.status.message).to.eql("success");
          });

          pm.test("Status code is 200", function() {
            pm.expect(pm.response.code).to.eql(200);
          });
        },
        auth(config, Var) {
          config.headers.Authorization = `Bearer ${pm[Var]("access_token")}`;
        }
      });

      postman[Request]({
        name: "PDPA",
        id: "6b1a5943-3e7a-4b28-9296-438f62f2e9ec",
        method: "GET",
        address: "{{https}}{{host}}{{url_pdpa}}",
        headers: {
          "X-Correlation-Id": "{{$randomUUID}}",
          TimeStamp: "{{timestamp}}",
          "Content-Signature": "{{signature_key}}"
        },
        pre() {
        },
        post(response) {
          var json = pm.response.json();

          pm.test("Message should be success", function() {
            pm.expect(json.status.message).to.eql("success");
          });

          pm.test("Status code is 200", function() {
            pm.expect(pm.response.code).to.eql(200);
          });
        },
        auth(config, Var) {
          config.headers.Authorization = `Bearer ${pm[Var]("access_token")}`;
        }
      });
    });
  });

  group("Block3.5", function() {
    group("My_Widget", function() {
      postman[Request]({
        name: "My_Tax",
        id: "071d6899-2800-4ee7-b56b-97379a035eb6",
        method: "POST",
        address: "{{https}}{{host}}{{url_my_widget}}",
        data:
          '{\n    "isLogin": true,\n    "widget_id": "0",\n    "callFrom": "my-tax"\n}',
        headers: {
          "X-Correlation-Id": "{{$randomUUID}}",
          deviceId: "{{deviceIdEncrypt}}",
          Timestamp: "{{timestamp}}"
        },
        pre() {
        },
        post(response) {
          var json = pm.response.json();

          pm.test("Message should be success", function() {
            pm.expect(json.status.message).to.eql("success");
          });

          pm.test("Status code is 200", function() {
            pm.expect(pm.response.code).to.eql(200);
          });
        }
      });
    })
  })
```

**K6 Log**
<img width="1676" alt="Screenshot 2024-07-30 at 17 59 48" src="https://github.com/user-attachments/assets/39ac736c-fbba-4c58-87d0-5d437d892614">

**Comment by thim81** [comment] 2024-07-30 18:20
hi @titanzx 

I rebuild your postman collection but it seems to properly render the headers.

In attachment, you can find the result.
[k6-result.zip.zip](https://github.com/user-attachments/files/16431966/k6-result.zip.zip)

Can you point out what is incorrect?

**Comment by titanzx** [comment] 2024-07-31 07:28
> hi @titanzx
> 
> I rebuild your postman collection but it seems to properly render the headers.
> 
> In attachment, you can find the result. [k6-result.zip.zip](https://github.com/user-attachments/files/16431966/k6-result.zip.zip)
> 
> Can you point out what is incorrect?

The request does not include an authorization header, but when the request is executed, the authorization is automatically added.

**Comment by thim81** [comment] 2024-07-31 07:42
I was focussed on the K6 script, but not on the K6 execution.
I spotted just now what you mean:
<img width="1052" alt="image" src="https://github.com/user-attachments/assets/40aad744-f7aa-44c6-86ea-42e931017797">

Thanks for helping to understand this unexpected behaviour.

I'll further investigate, to try to find the source.

**Comment by titanzx** [comment] 2024-07-31 07:46
> I was focussed on the K6 script, but not on the K6 execution. I spotted just now what you mean: <img alt="image" width="1052" src="https://private-user-images.githubusercontent.com/952446/353740349-40aad744-f7aa-44c6-86ea-42e931017797.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0MTIyMzQsIm5iZiI6MTcyMjQxMTkzNCwicGF0aCI6Ii85NTI0NDYvMzUzNzQwMzQ5LTQwYWFkNzQ0LWY3YWEtNDRjNi04NmVhLTQyZTkzMTAxNzc5Ny5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzMxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDczMVQwNzQ1MzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zMThiMDQyYTAzMGFhZmM4ZDQxNGNiZDI4NTNkNjJlYmE4M2U3MjI0NDU4N2FhYTU0Nzg4MThiYjc5OTM2MDQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.Ci2oOkToCT9FgfBl24BbtmkCvmDDqwm_84jf2Ysu1rM">
> 
> Thanks for helping to understand this unexpected behaviour.
> 
> I'll further investigate, to try to find the source.

Thank you

**Comment by thim81** [comment] 2024-07-31 17:45
@titanzx Found the cause and  just released a new version 1.12.0 that should solve your issue.

Can you update your project to use postman-to-k6 1.12.0 and verify if your issue is resolved?

**Comment by daniel-gonzaleza** [comment] 2024-08-12 19:08
Hey @thim81, found this thread while investigating an issue in our executions where headers used on some requests were being incorrectly reused by later requests. Updating to version 1.12.0 fixed the issue for us.

**Comment by thim81** [comment] 2024-08-13 09:29
@daniel-gonzaleza thanks for the validation and confirmation. 

I ll close the issue, based on your feedback. 

If you experiencing other issues, please do report them so we can investigate and improve postman-to-k6

**Closed** 2024-08-13 09:30 UTC
Labels: bug
